  -- New field - COMMANDE.ORIGIN
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'ORIGIN' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    ORIGIN  char(1) DEFAULT 'M';
END
GO

  -- New field - COMMANDE.ORIGINREF
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'ORIGINREF' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    ORIGINREF  VARCHAR(200);
END
GO

  -- New field - COMMANDE.EXPORTCOUNT
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'EXPORTCOUNT' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    EXPORTCOUNT int;
END
GO

  -- New field - COMMANDE.CONFIRMNO
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CONFIRMNO' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CONFIRMNO  VARCHAR(60);
END
GO

  -- New field - COMMANDE.CLIENTCIE
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CLIENTCIE' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CLIENTCIE VARCHAR(50);
END
GO

  -- New field - COMMANDE.CLIENTCNT
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CLIENTCNT' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CLIENTCNT VARCHAR(50);
END
GO


  -- New field - COMMANDE.CLIENTRUE1
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CLIENTRUE1' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CLIENTRUE1 VARCHAR(50);
END
GO


  -- New field - COMMANDE.CLIENTRUE2
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CLIENTRUE2' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CLIENTRUE2 VARCHAR(50);
END
GO


  -- New field - COMMANDE.CLIENTVILL
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CLIENTVILL' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CLIENTVILL VARCHAR(40);
END
GO


  -- New field - COMMANDE.CLIENTCP
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CLIENTCP' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CLIENTCP VARCHAR(7);
END
GO


  -- New field - COMMANDE.CLIENTPROV
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CLIENTPROV' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CLIENTPROV VARCHAR(40);
END
GO


  -- New field - COMMANDE.CLIENTPAYS
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CLIENTPAYS' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CLIENTPAYS VARCHAR(40);
END
GO

  -- New field - COMMANDE.CLIENTBP
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CLIENTBP' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CLIENTBP VARCHAR(30);
END
GO


  -- New field - COMMANDE.CLIENTTEL1
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CLIENTTEL1' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CLIENTTEL1 VARCHAR(20);
END
GO


  -- New field - COMMANDE.CLIENTTEL2
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CLIENTTEL2' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CLIENTTEL2 VARCHAR(20);
END
GO


  -- New field - COMMANDE.CLIENTTEL3
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CLIENTTEL3' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CLIENTTEL3 VARCHAR(20);
END
GO


  -- New field - COMMANDE.CLIENTFAX
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CLIENTFAX' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CLIENTFAX VARCHAR(20);
END
GO


  -- New field - COMMANDE.CLIENTEMAIL
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'CLIENTEMAIL' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    CLIENTEMAIL VARCHAR(80);
END
GO


 -- SITE
 
   -- New field - COMMANDE.SITECIE
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SITECIE' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SITECIE VARCHAR(50);
END
GO

  -- New field - COMMANDE.SITECNT
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SITECNT' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SITECNT VARCHAR(50);
END
GO


  -- New field - COMMANDE.SITERUE1
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SITERUE1' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SITERUE1 VARCHAR(50);
END
GO


  -- New field - COMMANDE.SITERUE2
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SITERUE2' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SITERUE2 VARCHAR(50);
END
GO


  -- New field - COMMANDE.SITEVILL
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SITEVILL' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SITEVILL VARCHAR(40);
END
GO


  -- New field - COMMANDE.SITECP
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SITECP' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SITECP VARCHAR(7);
END
GO


  -- New field - COMMANDE.SITEPROV
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SITEPROV' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SITEPROV VARCHAR(40);
END
GO


  -- New field - COMMANDE.SITEPAYS
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SITEPAYS' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SITEPAYS VARCHAR(40);
END
GO

  -- New field - COMMANDE.SITEBP
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SITEBP' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SITEBP VARCHAR(30);
END
GO


  -- New field - COMMANDE.SITETEL1
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SITETEL1' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SITETEL1 VARCHAR(20);
END
GO


  -- New field - COMMANDE.SITETEL2
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SITETEL2' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SITETEL2 VARCHAR(20);
END
GO


  -- New field - COMMANDE.SITETEL3
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SITETEL3' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SITETEL3 VARCHAR(20);
END
GO


  -- New field - COMMANDE.SITEFAX
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SITEFAX' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SITEFAX VARCHAR(20);
END
GO


  -- New field - COMMANDE.SITEEMAIL
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SITEEMAIL' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SITEEMAIL VARCHAR(80);
END
GO


-- SUPPLIER

  -- New field - COMMANDE.SUPPCIE
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SUPPCIE' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SUPPCIE VARCHAR(50);
END
GO

  -- New field - COMMANDE.SUPPCNT
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SUPPCNT' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SUPPCNT VARCHAR(50);
END
GO


  -- New field - COMMANDE.SUPPRUE1
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SUPPRUE1' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SUPPRUE1 VARCHAR(50);
END
GO


  -- New field - COMMANDE.SUPPRUE2
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SUPPRUE2' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SUPPRUE2 VARCHAR(50);
END
GO


  -- New field - COMMANDE.SUPPVILL
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SUPPVILL' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SUPPVILL VARCHAR(40);
END
GO


  -- New field - COMMANDE.SUPPCP
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SUPPCP' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SUPPCP VARCHAR(7);
END
GO


  -- New field - COMMANDE.SUPPPROV
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SUPPPROV' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SUPPPROV VARCHAR(40);
END
GO


  -- New field - COMMANDE.SUPPPAYS
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SUPPPAYS' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SUPPPAYS VARCHAR(40);
END
GO

  -- New field - COMMANDE.SUPPBP
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SUPPBP' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SUPPBP VARCHAR(30);
END
GO


  -- New field - COMMANDE.SUPPTEL1
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SUPPTEL1' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SUPPTEL1 VARCHAR(20);
END
GO


  -- New field - COMMANDE.SUPPTEL2
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SUPPTEL2' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SUPPTEL2 VARCHAR(20);
END
GO


  -- New field - COMMANDE.SUPPTEL3
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SUPPTEL3' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SUPPTEL3 VARCHAR(20);
END
GO


  -- New field - COMMANDE.SUPPFAX
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SUPPFAX' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SUPPFAX VARCHAR(20);
END
GO


  -- New field - COMMANDE.SUPPEMAIL
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMANDE'
    AND [COLUMN_NAME] = 'SUPPEMAIL' )
BEGIN
  ALTER TABLE
    COMMANDE
  ADD
    SUPPEMAIL VARCHAR(80);
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE Routine_Type = 'PROCEDURE' AND Specific_Name = 'up_COMMANDE_Update')
  DROP PROCEDURE up_COMMANDE_Update
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE Routine_Type = 'PROCEDURE' AND Specific_Name = 'up_COMMANDE_Update')
  DROP PROCEDURE up_COMMANDE_Update
GO

CREATE PROCEDURE [dbo].[up_COMMANDE_Update] (
  @UniqueId bigint,
  @COM_ID varchar(20),
  @COM_NO varchar(12),
  @SOU_ID varchar(20),
  @JOB_NO varchar(12),
  @DESCR varchar(60),
  @DATE_CREE datetime,
  @DATE_COM datetime,
  @DATE_LIVR datetime,
  @INSTRUCT text,
  @NOTES text,
  @ORDERED_ID varchar(20),
  @ORDERED_NO varchar(20),
  @BILLEDIDX int,
  @BILLED_ID varchar(20),
  @BILLED_NO varchar(20),
  @DELIVERIDX int,
  @DELIVER_ID varchar(20),
  @DELIVER_NO varchar(20),
  @COMTOTAL float,
  @ACCTRANSNO varchar(12),
  @STATUT int,
  @STATUTLIBF varchar(30), 
  @STATUTLIBE varchar(30), 
  @ORIGIN varchar(1), 
  @ORIGINREF varchar(200),
  @CONFIRMNO varchar(60),  
  @EXPORTCOUNT int,
  @CLIENTCIE   varchar(50) ,
  @CLIENTCNT   varchar(50) ,
  @CLIENTRUE1  varchar(50) ,
  @CLIENTRUE2  varchar(50) ,
  @CLIENTVILL  varchar(40) ,
  @CLIENTCP    varchar(7)  ,
  @CLIENTPROV  varchar(40) ,
  @CLIENTPAYS  varchar(40) ,
  @CLIENTBP    varchar(30) ,
  @CLIENTTEL1  varchar(20) ,
  @CLIENTTEL2  varchar(20) ,
  @CLIENTTEL3  varchar(20) ,
  @CLIENTFAX   varchar(20) ,
  @CLIENTEMAIL varchar(80) ,    
  @SITECIE   varchar(50) ,
  @SITECNT   varchar(50) ,
  @SITERUE1  varchar(50) ,
  @SITERUE2  varchar(50) ,
  @SITEVILL  varchar(40) ,
  @SITECP    varchar(7)  ,
  @SITEPROV  varchar(40) ,
  @SITEPAYS  varchar(40) ,
  @SITEBP    varchar(30) ,
  @SITETEL1  varchar(20) ,
  @SITETEL2  varchar(20) ,
  @SITETEL3  varchar(20) ,
  @SITEFAX   varchar(20) ,
  @SITEEMAIL varchar(80) ,    
  @SUPPCIE   varchar(50) ,
  @SUPPCNT   varchar(50) ,
  @SUPPRUE1  varchar(50) ,
  @SUPPRUE2  varchar(50) ,
  @SUPPVILL  varchar(40) ,
  @SUPPCP    varchar(7)  ,
  @SUPPPROV  varchar(40) ,
  @SUPPPAYS  varchar(40) ,
  @SUPPBP    varchar(30) ,
  @SUPPTEL1  varchar(20) ,
  @SUPPTEL2  varchar(20) ,
  @SUPPTEL3  varchar(20) ,
  @SUPPFAX   varchar(20) ,
  @SUPPEMAIL varchar(80)    
) AS

IF @UniqueId IS NULL
BEGIN
  --Insert new data into table
  INSERT INTO COMMANDE (
    [COM_ID],
    [COM_NO],
    [SOU_ID],
    [JOB_NO],
    [DESCR],
    [DATE_CREE],
    [DATE_COM],
    [DATE_LIVR],
    [INSTRUCT],
    [NOTES],
    [ORDERED_ID],
    [ORDERED_NO],
    [BILLEDIDX],
    [BILLED_ID],
    [BILLED_NO],
    [DELIVERIDX],
    [DELIVER_ID],
    [DELIVER_NO],
    [COMTOTAL],
    [ACCTRANSNO],
	[STATUT],
    [STATUTLIBF], 
    [STATUTLIBE],  
    [ORIGIN], 
    [ORIGINREF],  
    [CONFIRMNO],      
    [EXPORTCOUNT],     
    [CLIENTCIE],
    [CLIENTCNT],
    [CLIENTRUE1],
    [CLIENTRUE2],
    [CLIENTVILL],
    [CLIENTCP],
    [CLIENTPROV],
    [CLIENTPAYS],
    [CLIENTBP],
    [CLIENTTEL1],
    [CLIENTTEL2],
    [CLIENTTEL3],
    [CLIENTFAX],
    [CLIENTEMAIL],
    [SITECIE],
    [SITECNT],
    [SITERUE1],
    [SITERUE2],
    [SITEVILL],
    [SITECP],
    [SITEPROV],
    [SITEPAYS],
    [SITEBP],
    [SITETEL1],
    [SITETEL2],
    [SITETEL3],
    [SITEFAX],
    [SITEEMAIL],
    [SUPPCIE],
    [SUPPCNT],
    [SUPPRUE1],
    [SUPPRUE2],
    [SUPPVILL],
    [SUPPCP],
    [SUPPPROV],
    [SUPPPAYS],
    [SUPPBP],
    [SUPPTEL1],
    [SUPPTEL2],
    [SUPPTEL3],
    [SUPPFAX],
    [SUPPEMAIL],    
    SysDate)
  VALUES (
    @COM_ID,
    @COM_NO,
    @SOU_ID,
    @JOB_NO,
    @DESCR,
    @DATE_CREE,
    @DATE_COM,
    @DATE_LIVR,
    @INSTRUCT,
    @NOTES,
    @ORDERED_ID,
    @ORDERED_NO,
    @BILLEDIDX,
    @BILLED_ID,
    @BILLED_NO,
    @DELIVERIDX,
    @DELIVER_ID,
    @DELIVER_NO,
    @COMTOTAL,
    @ACCTRANSNO,
    @STATUT,
    @STATUTLIBF, 
    @STATUTLIBE,  
    @ORIGIN, 
    @ORIGINREF,     
    @CONFIRMNO,  
    @EXPORTCOUNT,   
    @CLIENTCIE  ,
    @CLIENTCNT  ,
    @CLIENTRUE1 ,
    @CLIENTRUE2 ,
    @CLIENTVILL ,
    @CLIENTCP   ,
    @CLIENTPROV ,
    @CLIENTPAYS ,
    @CLIENTBP   ,
    @CLIENTTEL1 ,
    @CLIENTTEL2 ,
    @CLIENTTEL3 ,
    @CLIENTFAX  ,
    @CLIENTEMAIL ,
    @SITECIE  ,
    @SITECNT  ,
    @SITERUE1 ,
    @SITERUE2 ,
    @SITEVILL ,
    @SITECP   ,
    @SITEPROV ,
    @SITEPAYS ,
    @SITEBP   ,
    @SITETEL1 ,
    @SITETEL2 ,
    @SITETEL3 ,
    @SITEFAX  ,
    @SITEEMAIL ,
    @SUPPCIE  ,
    @SUPPCNT  ,
    @SUPPRUE1 ,
    @SUPPRUE2 ,
    @SUPPVILL ,
    @SUPPCP   ,
    @SUPPPROV ,
    @SUPPPAYS ,
    @SUPPBP   ,
    @SUPPTEL1 ,
    @SUPPTEL2 ,
    @SUPPTEL3 ,
    @SUPPFAX  ,
    @SUPPEMAIL ,
    GETDATE())

  --Return new ID
  RETURN @@IDENTITY
END ELSE
BEGIN
  --Update data into table
  UPDATE
    COMMANDE
  SET
    [COM_ID] = @COM_ID,
    [COM_NO] = @COM_NO,
    [SOU_ID] = @SOU_ID,
    [JOB_NO] = @JOB_NO,
    [DESCR] = @DESCR,
    [DATE_CREE] = @DATE_CREE,
    [DATE_COM] = @DATE_COM,
    [DATE_LIVR] = @DATE_LIVR,
    [INSTRUCT] = @INSTRUCT,
    [NOTES] = @NOTES,
    [ORDERED_ID] = @ORDERED_ID,
    [ORDERED_NO] = @ORDERED_NO,
    [BILLEDIDX] = @BILLEDIDX,
    [BILLED_ID] = @BILLED_ID,
    [BILLED_NO] = @BILLED_NO,
    [DELIVERIDX] = @DELIVERIDX,
    [DELIVER_ID] = @DELIVER_ID,
    [DELIVER_NO] = @DELIVER_NO,
    [COMTOTAL] = @COMTOTAL,
    [ACCTRANSNO] = @ACCTRANSNO,
    [STATUT] = @STATUT,
    [STATUTLIBF]  = @STATUTLIBF,
    [STATUTLIBE]  = @STATUTLIBE,
    [ORIGIN]      = @ORIGIN, 
    [ORIGINREF]   = @ORIGINREF,  
    [CONFIRMNO]   = @CONFIRMNO,      
    [EXPORTCOUNT]   = @EXPORTCOUNT,      
    [CLIENTCIE]   = @CLIENTCIE,
    [CLIENTCNT]   = @CLIENTCNT,
    [CLIENTRUE1]  = @CLIENTRUE1,
    [CLIENTRUE2]  = @CLIENTRUE2,
    [CLIENTVILL]  = @CLIENTVILL,
    [CLIENTCP]    = @CLIENTCP,
    [CLIENTPROV]  = @CLIENTPROV,
    [CLIENTPAYS]  = @CLIENTPAYS,
    [CLIENTBP]    = @CLIENTBP,
    [CLIENTTEL1]  = @CLIENTTEL1,
    [CLIENTTEL2]  = @CLIENTTEL2,
    [CLIENTTEL3]  = @CLIENTTEL3,
    [CLIENTFAX]   = @CLIENTFAX,
    [CLIENTEMAIL] = @CLIENTEMAIL,
    [SITECIE]   = @SITECIE,
    [SITECNT]   = @SITECNT,
    [SITERUE1]  = @SITERUE1,
    [SITERUE2]  = @SITERUE2,
    [SITEVILL]  = @SITEVILL,
    [SITECP]    = @SITECP,
    [SITEPROV]  = @SITEPROV,
    [SITEPAYS]  = @SITEPAYS,
    [SITEBP]    = @SITEBP,
    [SITETEL1]  = @SITETEL1,
    [SITETEL2]  = @SITETEL2,
    [SITETEL3]  = @SITETEL3,
    [SITEFAX]   = @SITEFAX,
    [SITEEMAIL] = @SITEEMAIL,
    [SUPPCIE]   = @SUPPCIE,
    [SUPPCNT]   = @SUPPCNT,
    [SUPPRUE1]  = @SUPPRUE1,
    [SUPPRUE2]  = @SUPPRUE2,
    [SUPPVILL]  = @SUPPVILL,
    [SUPPCP]    = @SUPPCP,
    [SUPPPROV]  = @SUPPPROV,
    [SUPPPAYS]  = @SUPPPAYS,
    [SUPPBP]    = @SUPPBP,
    [SUPPTEL1]  = @SUPPTEL1,
    [SUPPTEL2]  = @SUPPTEL2,
    [SUPPTEL3]  = @SUPPTEL3,
    [SUPPFAX]   = @SUPPFAX,
    [SUPPEMAIL] = @SUPPEMAIL,
    SysDate = GETDATE()
  WHERE
    UniqueId = @UniqueId

  --Return updated ID
  RETURN @UniqueId
END
GO

  -- New field - COMMITEM.WEBADDED
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'COMMITEM'
    AND [COLUMN_NAME] = 'WEBADDED' )
BEGIN
  ALTER TABLE
    COMMITEM
  ADD
    WEBADDED  BIT DEFAULT 0;
END
GO



IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE Routine_Type = 'PROCEDURE' AND Specific_Name = 'up_COMMITEM_Update')
  DROP PROCEDURE up_COMMITEM_Update
GO

CREATE PROCEDURE [dbo].[up_COMMITEM_Update] (
  @UniqueId bigint,
  @COM_ID varchar(20),
  @ORDRE varchar(6),
  @PRO_ID varchar(20),
  @CLEMANU varchar(30),
  @CLEDIST varchar(20),
  @CLEPERS varchar(20),
  @PRO_TYPE varchar(1),
  @DESCR varchar(60),
  @QTE_TOT float,
  @COUBRUTUNI float,
  @COUUM varchar(2),
  @COUESC float,
  @PROMCOUNET float,
  @QPP float,
  @MULCOM float,
  @CODEIMPR varchar(2),
  @WEBADDED bit,
  @NOTES      text        = '' -- Update V2.#0001
) AS

IF @UniqueId IS NULL
BEGIN
  --Insert new data into table
  INSERT INTO COMMITEM (
    [COM_ID],
    [ORDRE],
    [PRO_ID],
    [CLEMANU],
    [CLEDIST],
    [CLEPERS],
    [PRO_TYPE],
    [DESCR],
    [QTE_TOT],
    [COUBRUTUNI],
    [COUUM],
    [COUESC],
    [PROMCOUNET],
    [QPP],
    [MULCOM],
    [CODEIMPR],
    [WEBADDED],
    [NOTES],      -- Update V2.#0001
    SysDate)
  VALUES (
    @COM_ID,
    @ORDRE,
    @PRO_ID,
    @CLEMANU,
    @CLEDIST,
    @CLEPERS,
    @PRO_TYPE,
    @DESCR,
    @QTE_TOT,
    @COUBRUTUNI,
    @COUUM,
    @COUESC,
    @PROMCOUNET,
    @QPP,
    @MULCOM,
    @CODEIMPR,
    @WEBADDED,
    @NOTES,     -- Update V2.#0001
    GETDATE())

  --Return new ID
  RETURN @@IDENTITY
END ELSE
BEGIN
  --Update data into table
  UPDATE
    COMMITEM
  SET
    [COM_ID] = @COM_ID,
    [ORDRE] = @ORDRE,
    [PRO_ID] = @PRO_ID,
    [CLEMANU] = @CLEMANU,
    [CLEDIST] = @CLEDIST,
    [CLEPERS] = @CLEPERS,
    [PRO_TYPE] = @PRO_TYPE,
    [DESCR] = @DESCR,
    [QTE_TOT] = @QTE_TOT,
    [COUBRUTUNI] = @COUBRUTUNI,
    [COUUM] = @COUUM,
    [COUESC] = @COUESC,
    [PROMCOUNET] = @PROMCOUNET,
    [QPP] = @QPP,
    [MULCOM] = @MULCOM,
    [CODEIMPR] = @CODEIMPR,
    [WEBADDED] = @WEBADDED,
    [NOTES] = @NOTES,           -- Update V2.#0001
    SysDate = GETDATE()
  WHERE
    UniqueId = @UniqueId

  --Return updated ID
  RETURN @UniqueId
END
GO

  -- New field - BDEE.ORDERLOG
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'BDEE'
    AND [COLUMN_NAME] = 'ORDERLOG' )
BEGIN
  ALTER TABLE
    BDEE
  ADD
    ORDERLOG  VARCHAR(100);
END
GO

  -- New field - BDEE.ORDERPLOG
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'BDEE'
    AND [COLUMN_NAME] = 'ORDERPLOG' )
BEGIN
  ALTER TABLE
    BDEE
  ADD
    ORDERPLOG  VARCHAR(100);
END
GO
  -- New field - BDEE.ORDERCONF
IF NOT EXISTS (
  SELECT 
    TOP 1 *
  FROM 
    INFORMATION_SCHEMA.COLUMNS
  WHERE 
        [TABLE_NAME]  = 'BDEE'
    AND [COLUMN_NAME] = 'ORDERCONF' )
BEGIN
  ALTER TABLE
    BDEE
  ADD
    ORDERCONF  VARCHAR(100);
END
GO

