SET ANSI_WARNINGS OFF;
GO

--------------------------------------


UPDATE CM SET     	
    CM.ORDERED_NO = Addr.NUMERO,
    CM.SUPPCIE    = Addr.NOMCIE,
    CM.SUPPCNT    = Addr.CONTACT,
    CM.SUPPRUE1   = Addr.RUE1,
    CM.SUPPRUE2   = Addr.RUE2,
    CM.SUPPCP     = Addr.CODEPOSTAL,
    CM.SUPPVILL   = Addr.VILLE,
    CM.SUPPPROV   = Addr.PROVINCE,
    CM.SUPPPAYS   = Addr.PAYS,
    CM.SUPPTEL1   = Addr.TEL1,
    CM.SUPPTEL2   = Addr.TEL2,
    CM.SUPPTEL3   = Addr.TEL3,
    CM.SUPPFAX    = Addr.FAX,
    CM.SUPPBP     = Addr.BOITEPOSTA,
    CM.SUPPEMAIL  = Addr.EMAIL

FROM COMMANDE CM INNER JOIN CLIENTS Addr  
  ON CM.ORDERED_ID = Addr.CLI_ID     
WHERE         
    CM.SUPPCIE    IS NULL AND
    CM.SUPPCNT    IS NULL AND
    CM.SUPPRUE1   IS NULL AND
    CM.SUPPRUE2   IS NULL AND
    CM.SUPPCP     IS NULL AND
    CM.SUPPVILL   IS NULL AND
    CM.SUPPPROV   IS NULL AND
    CM.SUPPPAYS   IS NULL AND
    CM.SUPPTEL1   IS NULL AND
    CM.SUPPTEL2   IS NULL AND
    CM.SUPPTEL3   IS NULL AND
    CM.SUPPFAX    IS NULL AND
    CM.SUPPBP     IS NULL AND
    CM.SUPPEMAIL  IS NULL
GO


UPDATE CM SET 
    CM.BILLED_NO  = Addr.NUMERO,
    CM.CLIENTCIE  = Addr.NOMCIE,
    CM.CLIENTCNT  = Addr.CONTACT,
    CM.CLIENTRUE1 = Addr.RUE1,
    CM.CLIENTRUE2 = Addr.RUE2,
    CM.CLIENTCP   = Addr.CODEPOSTAL,
    CM.CLIENTVILL = Addr.VILLE,
    CM.CLIENTPROV = Addr.PROVINCE,
    CM.CLIENTPAYS = Addr.PAYS,
    CM.CLIENTTEL1 = Addr.TEL1,
    CM.CLIENTTEL2 = Addr.TEL2,
    CM.CLIENTTEL3 = Addr.TEL3,
    CM.CLIENTFAX  = Addr.FAX,
    CM.CLIENTBP   = Addr.BOITEPOSTA,
    CM.CLIENTEMAIL= Addr.EMAIL

FROM COMMANDE CM INNER JOIN CLIENTS Addr
    ON CM.BILLED_ID  = Addr.CLI_ID
WHERE 
  ((CM.BILLEDIDX = 1) OR (CM.BILLEDIDX = 2)) AND    
    CM.BILLED_ID   IS NOT NULL AND    
    CM.CLIENTCIE   IS     NULL AND
    CM.CLIENTCNT   IS     NULL AND
    CM.CLIENTRUE1  IS     NULL AND
    CM.CLIENTRUE2  IS     NULL AND
    CM.CLIENTCP    IS     NULL AND
    CM.CLIENTVILL  IS     NULL AND
    CM.CLIENTPROV  IS     NULL AND
    CM.CLIENTPAYS  IS     NULL AND
    CM.CLIENTTEL1  IS     NULL AND
    CM.CLIENTTEL2  IS     NULL AND
    CM.CLIENTTEL3  IS     NULL AND
    CM.CLIENTFAX   IS     NULL AND
    CM.CLIENTBP    IS     NULL AND
    CM.CLIENTEMAIL IS     NULL
GO

UPDATE CM SET  
  CM.DELIVER_NO= Addr.NUMERO,
  CM.SITECIE   = Addr.NOMCIE,
  CM.SITECNT   = Addr.CONTACT,
  CM.SITERUE1  = Addr.RUE1,
  CM.SITERUE2  = Addr.RUE2,
  CM.SITECP    = Addr.CODEPOSTAL,
  CM.SITEVILL  = Addr.VILLE,
  CM.SITEPROV  = Addr.PROVINCE,
  CM.SITEPAYS  = Addr.PAYS,
  CM.SITETEL1  = Addr.TEL1,
  CM.SITETEL2  = Addr.TEL2,
  CM.SITETEL3  = Addr.TEL3,
  CM.SITEFAX   = Addr.FAX,
  CM.SITEBP    = Addr.BOITEPOSTA,
  CM.SITEEMAIL = Addr.EMAIL

FROM COMMANDE CM INNER JOIN CLIENTS Addr 
 ON CM.DELIVER_ID= Addr.CLI_ID
WHERE
  ((CM.DELIVERIDX = 1) OR (CM.DELIVERIDX = 2)) AND
  CM.DELIVER_ID IS NOT NULL AND  
  CM.SITECIE    IS     NULL AND
  CM.SITECNT    IS     NULL AND
  CM.SITERUE1   IS     NULL AND
  CM.SITERUE2   IS     NULL AND
  CM.SITECP     IS     NULL AND
  CM.SITEVILL   IS     NULL AND
  CM.SITEPROV   IS     NULL AND
  CM.SITEPAYS   IS     NULL AND
  CM.SITETEL1   IS     NULL AND
  CM.SITETEL2   IS     NULL AND
  CM.SITETEL3   IS     NULL AND
  CM.SITEFAX    IS     NULL AND
  CM.SITEBP     IS     NULL AND
  CM.SITEEMAIL  IS     NULL
GO



SET ANSI_WARNINGS ON;
GO
