-- unload_dr_submissions.sql — reverses load_dr_submissions.sql through the official procedures only.
-- up_DeleteSoumis_Full (V3_UpdateDatabase.sql:1660) cascades SOUMIS + SOUREL, SOUBLO, SOUDIV, SOUAMD,
-- SOUWEBLOG, SOUPRO, SOUENS, SOUENSCO, SOULOTS, SOULOTSCO for one SOU_ID (@DeleteHeader = 1 removes the header).
SET NOCOUNT ON;
EXEC dbo.up_DeleteSoumis_Full @DeleteSOU_ID = 'S-1844', @DeleteHeader = 1;
EXEC dbo.up_DeleteSoumis_Full @DeleteSOU_ID = '1400-INDUSTRIEL', @DeleteHeader = 1;

DECLARE @id BIGINT;
SELECT @id = UniqueId FROM ENSEMBLE WHERE ENS_ID = 'DR:S-1844-FORFAIT';
IF @id IS NOT NULL EXEC dbo.up_ENSEMBLE_Delete @UniqueId = @id;

SET @id = NULL;
SELECT @id = UniqueId FROM CLIENTS WHERE CLI_ID = 'LC2000';
IF @id IS NOT NULL EXEC dbo.up_CLIENTS_Delete @UniqueId = @id;

SELECT 'SOUMIS' t, COUNT(*) n FROM SOUMIS WHERE SOU_ID IN ('S-1844','1400-INDUSTRIEL')
UNION ALL SELECT 'SOUREL', COUNT(*) FROM SOUREL WHERE SOU_ID IN ('S-1844','1400-INDUSTRIEL')
UNION ALL SELECT 'SOUENS', COUNT(*) FROM SOUENS WHERE SOU_ID IN ('S-1844','1400-INDUSTRIEL')
UNION ALL SELECT 'SOUPRO', COUNT(*) FROM SOUPRO WHERE SOU_ID IN ('S-1844','1400-INDUSTRIEL')
UNION ALL SELECT 'ENSEMBLE', COUNT(*) FROM ENSEMBLE WHERE ENS_ID = 'DR:S-1844-FORFAIT'
UNION ALL SELECT 'CLIENTS', COUNT(*) FROM CLIENTS WHERE CLI_ID = 'LC2000';
