-- verify_dr_submissions.sql — read-only proof of what load_dr_submissions.sql put in the live EE database.
SET NOCOUNT ON;
SELECT 'SOUMIS' AS tbl, SOU_ID, NODOC, DESCDOC, CONVERT(varchar(10), DATEDOC, 120) AS DATEDOC, CLIENTNO, CLIENTCIE, SITECIE, SITERUE1, SITEVILLE,
       CAST(MATCOUTREL AS decimal(18,2)) AS MATCOUTREL, CAST(MATVENDCAL AS decimal(18,2)) AS MATVENDCAL,
       CAST(AUTCOUTCAL AS decimal(18,2)) AS AUTCOUTCAL, CAST(AUTVENDCAL AS decimal(18,2)) AS AUTVENDCAL,
       TOTCALCULE, EST_NAME, EXTFILE
  FROM SOUMIS WHERE SOU_ID IN ('S-1844','1400-INDUSTRIEL') ORDER BY SOU_ID;
SELECT 'SOUREL' AS tbl, SOU_ID, BLO_ID, DIV_ID, TYPERELEVE, TYPEITEM, ORDRE, ITEM_ID, DESCR, QTE, QTEUM, PROFIT, CODEIMPR,
       CAST(COUTANBRUT AS decimal(18,2)) AS COUTANBRUT
  FROM SOUREL WHERE SOU_ID IN ('S-1844','1400-INDUSTRIEL') ORDER BY SOU_ID;
SELECT 'SOUPRO' AS tbl, SOU_ID, PRO_ID, CLEMANU, CLEDIST, CLEPERS, [DESC], QTEOTH, QTEENS, QTELOT,
       CAST(COUBRUTUNI AS decimal(18,2)) AS COUBRUTUNI, COUUM, QPP, CONVERT(varchar(10), DATECOUT, 120) AS DATECOUT,
       CAST(UnitSelling AS decimal(18,2)) AS UnitSelling, CALCTIMSTP
  FROM SOUPRO WHERE SOU_ID IN ('S-1844','1400-INDUSTRIEL');
SELECT 'SOUENS' AS tbl, SOU_ID, ENS_ID, ENS_ORG_ID, [DESC], QTETOT, COUUM, CLEPERS, TEMPUNI, PROFIT
  FROM SOUENS WHERE SOU_ID IN ('S-1844','1400-INDUSTRIEL');
SELECT 'ENSEMBLE' AS tbl, ENS_ID, CLEPERS, [DESC], COUUM, PROFIT, TEMPUNI, CONVERT(varchar(10), DATECREE, 120) AS DATECREE, [SYSTEM], USES_DISC
  FROM ENSEMBLE WHERE ENS_ID LIKE 'DR:%';
SELECT 'SOUBLO' AS tbl, SOU_ID, BLO_ID, [DESC], MULT, ORDRE FROM SOUBLO WHERE SOU_ID IN ('S-1844','1400-INDUSTRIEL');
SELECT 'SOUDIV' AS tbl, SOU_ID, DIV_ID, [DESC], ORDRE FROM SOUDIV WHERE SOU_ID IN ('S-1844','1400-INDUSTRIEL');
SELECT 'CLIENTS' AS tbl, CLI_ID, NOMCIE, CONTACT, RUE1, VILLE, CODEPOSTAL, PROVINCE, EMAIL FROM CLIENTS WHERE CLI_ID = 'LC2000';
SELECT 'ENSCOMPO/SOUENSCO' AS tbl, (SELECT COUNT(*) FROM ENSCOMPO WHERE ENS_ID LIKE 'DR:%') AS enscompo,
       (SELECT COUNT(*) FROM SOUENSCO WHERE SOU_ID IN ('S-1844','1400-INDUSTRIEL')) AS souensco;
SELECT 'ROWCOUNTS' AS tbl, (SELECT COUNT(*) FROM SOUMIS) soumis, (SELECT COUNT(*) FROM SOUREL) sourel, (SELECT COUNT(*) FROM SOUPRO) soupro,
       (SELECT COUNT(*) FROM SOUENS) souens, (SELECT COUNT(*) FROM ENSEMBLE) ensemble, (SELECT COUNT(*) FROM CLIENTS) clients,
       (SELECT COUNT(*) FROM SOUBLO) soublo, (SELECT COUNT(*) FROM SOUDIV) soudiv;
