"""Profile Dupuis gold .qpl takeoffs. Run from data/dossiers: python3 tools/dupuis_profile.py"""
import xml.etree.ElementTree as ET,collections,glob,sys
for f in sorted(glob.glob('S-*/reference/*Dupuis*.qpl')):
    t=ET.parse(f).getroot()
    plans=t.findall('Plans/Plan'); grp=t.findall('Plans/Group')
    ee=t.findall('Plans/Group/EEExchangeData')
    sc=collections.Counter((s.get('Value'),s.get('Type'),s.get('SetManually')) for s in t.iter('Scale'))
    ctr=t.findall('.//Counter'); ln=t.findall('.//Line')
    shp=collections.Counter(c.get('Shape') for c in ctr)
    gids=set(c.get('GroupID') for c in ctr+ln)
    eegid=set(g.get('GroupID') for g in grp if g.find('EEExchangeData') is not None)
    names=collections.Counter()
    for c in ctr: names[c.get('Name')]+=len(c)
    lnames=collections.Counter()
    for l in ln: lnames[l.get('Name')]+=len(l)
    active=sum(1 for p in plans if p.find('Layers//Counter') is not None or p.find('Layers//Line') is not None)
    print('==',f); print(' plans',len(plans),'with objects',active,'groups',len(grp),'EE',len(ee),'prices',len(t.findall('Prices/Price')))
    print(' scales',dict(sc))
    print(' counters',len(ctr),'elements',sum(len(c) for c in ctr),'distinct names',len(names),'shapes',dict(shp))
    print(' lines',len(ln),'segments',sum(len(l) for l in ln),'names',dict(lnames.most_common(8)))
    print(' areas',len(t.findall('.//Area')),'rects',len(t.findall('.//Rectangle')))
    print(' counter/line groupIDs',len(gids),'with EE link',len(gids&eegid))
    print(' top counters',names.most_common(12))
    for e in ee[:4]: print('  EE',e.attrib)
    print(' EE ItemTypes',collections.Counter(e.get('ItemType') for e in ee))
