-- Cleanup of the rows created by qpl_to_eewin_sql.py for ZZTEST-PE1844 (official delete procedures only).
SET NOCOUNT ON;
EXEC dbo.up_DeleteSoumis_Full @DeleteSOU_ID='ZZTEST-PE1844', @DeleteHeader=1;
DECLARE @uid bigint;
DECLARE c_ENSCOMPO CURSOR LOCAL FOR SELECT UniqueId FROM ENSCOMPO WHERE ENS_ID IN ('ENSAFF5D05713B179C81','ENS9E93142F911561EE1');
OPEN c_ENSCOMPO; FETCH NEXT FROM c_ENSCOMPO INTO @uid; WHILE @@FETCH_STATUS=0 BEGIN EXEC dbo.up_ENSCOMPO_Delete @UniqueId=@uid; FETCH NEXT FROM c_ENSCOMPO INTO @uid; END; CLOSE c_ENSCOMPO; DEALLOCATE c_ENSCOMPO;
DECLARE c_ENSEMBLE CURSOR LOCAL FOR SELECT UniqueId FROM ENSEMBLE WHERE ENS_ID IN ('ENSAFF5D05713B179C81','ENS9E93142F911561EE1');
OPEN c_ENSEMBLE; FETCH NEXT FROM c_ENSEMBLE INTO @uid; WHILE @@FETCH_STATUS=0 BEGIN EXEC dbo.up_ENSEMBLE_Delete @UniqueId=@uid; FETCH NEXT FROM c_ENSEMBLE INTO @uid; END; CLOSE c_ENSEMBLE; DEALLOCATE c_ENSEMBLE;
DECLARE c_PRODUITS CURSOR LOCAL FOR SELECT UniqueId FROM PRODUITS WHERE PRO_ID LIKE 'ZZPE-%';
OPEN c_PRODUITS; FETCH NEXT FROM c_PRODUITS INTO @uid; WHILE @@FETCH_STATUS=0 BEGIN EXEC dbo.up_PRODUITS_Delete @UniqueId=@uid; FETCH NEXT FROM c_PRODUITS INTO @uid; END; CLOSE c_PRODUITS; DEALLOCATE c_PRODUITS;
SELECT (SELECT COUNT(*) FROM SOUMIS WHERE SOU_ID='ZZTEST-PE1844') AS soumis, (SELECT COUNT(*) FROM SOUREL WHERE SOU_ID='ZZTEST-PE1844') AS sourel, (SELECT COUNT(*) FROM SOUPRO WHERE SOU_ID='ZZTEST-PE1844') AS soupro, (SELECT COUNT(*) FROM SOUENS WHERE SOU_ID='ZZTEST-PE1844') AS souens, (SELECT COUNT(*) FROM SOUENSCO WHERE SOU_ID='ZZTEST-PE1844') AS souensco, (SELECT COUNT(*) FROM SOUBLO WHERE SOU_ID='ZZTEST-PE1844') AS soublo, (SELECT COUNT(*) FROM SOUDIV WHERE SOU_ID='ZZTEST-PE1844') AS soudiv, (SELECT COUNT(*) FROM ENSEMBLE WHERE ENS_ID IN ('ENSAFF5D05713B179C81','ENS9E93142F911561EE1')) AS ensemble, (SELECT COUNT(*) FROM PRODUITS WHERE PRO_ID LIKE 'ZZPE-%') AS produits;
