-- Generated by qpl_to_eewin_sql.py from S-1844-Dupuis-PlanExpert.qpl
-- Project: S-1844 | plans: 35 | drawn objects: 68 | EE-linked groups: 2 | Prices: 66 (CostEach != 0: 0)
SET NOCOUNT ON;
DECLARE @SOU_ID varchar(20) = 'ZZTEST-PE1844';
IF EXISTS (SELECT 1 FROM SOUMIS WHERE SOU_ID = @SOU_ID) BEGIN RAISERROR('SOU_ID already exists', 16, 1); RETURN; END;
PRINT '=== 0. SYNTHETIC catalogue (composition invented for the proof; only ENS_ID/CLEPERS/DESC come from the .qpl) ===';
EXEC dbo.up_PRODUITS_Update @UniqueId=NULL, @PRO_ID='ZZPE-CONDUIT', @PRO_ID_OLD='', @PRO_ID_NEW='', @PRO_ID_Parent='', @CLEMANU='SYNTH-EMT', @CLEPERS='', @CLEDIST='', @CODEUPC='', @CODECAT='ZZ', @DESCDIST='SYNTHETIC conduit', @DESC='SYNTHETIC conduit (per 100 ft)', @COUBRUTUNI=100.00, @COUUM='CF', @QPP=0, @COUESC=0, @PROMCOUNET=0, @PROFIT=0, @MULCOM=1, @TEMPUNI=2.0, @TEMPUM='CF', @CODEFOUR='ZZ', @NOUVEAU='N', @DNR='N', @DATECOUT='2026-01-01', @DATECOUNET=NULL, @RESCOUNET=0, @DATECREE='2026-01-01', @PATHPICT='', @PATHSPEC='', @IMAGE='N', @USER1='', @USER2='', @PREFERED='N', @ACC_NO='', @ACH_NO='';
EXEC dbo.up_PRODUITS_Update @UniqueId=NULL, @PRO_ID='ZZPE-WIRE', @PRO_ID_OLD='', @PRO_ID_NEW='', @PRO_ID_Parent='', @CLEMANU='SYNTH-W12', @CLEPERS='', @CLEDIST='', @CODEUPC='', @CODECAT='ZZ', @DESCDIST='SYNTHETIC wire', @DESC='SYNTHETIC wire #12 (per 100 ft)', @COUBRUTUNI=40.00, @COUUM='CF', @QPP=0, @COUESC=0, @PROMCOUNET=0, @PROFIT=0, @MULCOM=1, @TEMPUNI=1.0, @TEMPUM='CF', @CODEFOUR='ZZ', @NOUVEAU='N', @DNR='N', @DATECOUT='2026-01-01', @DATECOUNET=NULL, @RESCOUNET=0, @DATECREE='2026-01-01', @PATHPICT='', @PATHSPEC='', @IMAGE='N', @USER1='', @USER2='', @PREFERED='N', @ACC_NO='', @ACH_NO='';
EXEC dbo.up_ENSEMBLE_Update @UniqueId=NULL, @ENS_ID='ENSAFF5D05713B179C81', @CLEPERS='19PE0.75 #12', @DESC='SYNTHETIC conduit 3/4 07c12', @COUUM='F', @PROFIT=0, @TEMPSEC=0, @TEMPUNI=0, @TEMPUM='F', @DATECREE='2026-01-01', @OLDESTPROD='2026-01-01', @SYSTEM=0, @USES_DISC=0;
EXEC dbo.up_ENSCOMPO_Update @UniqueId=NULL, @ENS_ID='ENSAFF5D05713B179C81', @ORDRE='000010', @PRO_ID='ZZPE-CONDUIT', @QTE=1, @QTEUM='F', @TYPRATIO='L', @DIV=1, @DIVUM='F';
EXEC dbo.up_ENSCOMPO_Update @UniqueId=NULL, @ENS_ID='ENSAFF5D05713B179C81', @ORDRE='000020', @PRO_ID='ZZPE-WIRE', @QTE=7, @QTEUM='F', @TYPRATIO='L', @DIV=1, @DIVUM='F';
EXEC dbo.up_ENSEMBLE_Update @UniqueId=NULL, @ENS_ID='ENS9E93142F911561EE1', @CLEPERS='19PE2 #12', @DESC='SYNTHETIC conduit 2 33c12', @COUUM='F', @PROFIT=0, @TEMPSEC=0, @TEMPUNI=0, @TEMPUM='F', @DATECREE='2026-01-01', @OLDESTPROD='2026-01-01', @SYSTEM=0, @USES_DISC=0;
EXEC dbo.up_ENSCOMPO_Update @UniqueId=NULL, @ENS_ID='ENS9E93142F911561EE1', @ORDRE='000010', @PRO_ID='ZZPE-CONDUIT', @QTE=1, @QTEUM='F', @TYPRATIO='L', @DIV=1, @DIVUM='F';
EXEC dbo.up_ENSCOMPO_Update @UniqueId=NULL, @ENS_ID='ENS9E93142F911561EE1', @ORDRE='000020', @PRO_ID='ZZPE-WIRE', @QTE=33, @QTEUM='F', @TYPRATIO='L', @DIV=1, @DIVUM='F';
PRINT '=== 1. Header (SOUMIS): EXTFILE = the .qpl file, UMPLAN = unit of plan measurements ===';
DECLARE @NOW datetime = GETDATE();
EXEC dbo.up_SOUMIS_Update @UniqueId=NULL, @SOU_ID=@SOU_ID, @ORIGIN='', @ORIGINREF='', @EXTAPP='', @EXTFILE='S-1844-Dupuis-PlanExpert.qpl',
  @NODOC='ZZTEST-PE1844', @DESCDOC='S-1844', @DATECREE=@NOW, @DATEDOC=@NOW, @DATEEXP=NULL,
  @REF_ID='', @STATUT=0, @NOCOMMANDE='', @NOTEINTERN='', @CLIENTNO='', @CLIENTCIE='', @CLIENTCNT='', @CLIENTRUE1='', @CLIENTRUE2='',
  @CLIENTVILL='', @CLIENTCP='', @CLIENTPROV='', @CLIENTPAYS='', @CLIENTBP='', @CLIENTTEL1='', @CLIENTTEL2='', @CLIENTTEL3='', @CLIENTFAX='', @CLIENTEMAI='',
  @MEMESITE=1, @SITENO='', @SITECIE='', @SITECNT='', @SITERUE1='', @SITERUE2='', @SITEVILLE='', @SITECP='', @SITEPROV='', @SITEPAYS='', @SITEBP='',
  @SITETEL1='', @SITETEL2='', @SITETEL3='', @SITEFAX='', @SITEEMAIL='',
  @MATTOTALMD=0, @NOTEPRINC='', @MATCOUTREL=0, @MATCOUTLOT=0, @MATVENDCAL=0, @MATPORTTVP=0, @SERCOUTCAL=0, @SERVENDCAL=0, @SERHRESCAL=0, @SERPORTTVP=0,
  @AUTCOUTCAL=0, @AUTVENDCAL=0, @AUTPORTTVP=0, @OPTIONSSOM='', @MATCOUTMO=0, @SERCOUTMO=0, @AUTCOUTMO=0, @MATADMPC=0, @SERADMPC=0, @AUTADMPC=0,
  @MATADMMO=0, @SERADMMO=0, @AUTADMMO=0, @MATPROFPC=0, @SERPROFPC=0, @AUTPROFPC=0, @MATPROFMO=0, @SERPROFMO=0, @AUTPROFMO=0,
  @GLOBAJUPC=0, @GLOBAJUMO=0, @GLOBEXPLIC='', @GLOBAJU2PC=0, @GLOBAJU2MO=0, @GLOBEXPL2='', @OPTIONSIMP='', @OPIMPADJMA='', @OPIMPADJLA='', @OPIMPADJOT='', @NOTEBAS='',
  @MATTAXAB1=0, @MATTAXAB2=0, @MATTAXAB3=0, @MATTAXAB4=0, @MATTAXAB5=0, @MATTAXAB6=0, @SERTAXAB1=0, @SERTAXAB2=0, @SERTAXAB3=0, @SERTAXAB4=0, @SERTAXAB5=0, @SERTAXAB6=0,
  @AUTTAXAB1=0, @AUTTAXAB2=0, @AUTTAXAB3=0, @AUTTAXAB4=0, @AUTTAXAB5=0, @AUTTAXAB6=0, @TAXTYPCAL=0, @AJUTAXAB1=0, @AJUTAXAB2=0, @AJUTAXAB3=0, @AJUTAXAB4=0, @AJUTAXAB5=0,
  @TOTTAXFED=0, @TOTTAXPRV=0, @TAX_ID='', @APPLIQUTVF=1, @APPLIQUTVP=1, @TVPSURCOUT=1, @TOTCALCULE=0, @CALCTIMSTP='', @UMPLAN='F',
  @TYPEPROF='C', @MATPROFDEF=0, @TYPESRVPRO='C', @TAUXMD=0, @NUMLOTEXP=0, @SYSTEM=0, @USER1='', @USER2='', @EST_NAME='', @ACCTRANSNO='', @PRJTRANSNO='',
  @STATUTLIBF='', @STATUTLIBE='', @USER_ID='', @BRANCH_ID='', @OWC='';
PRINT '=== 2. One block per plan that carries a linked object (SOUBLO, BLO_ID numeric for fn_MultBlock), one division per layer (SOUDIV) ===';
EXEC dbo.up_SOUBLO_Update @UniqueId=NULL, @SOU_ID=@SOU_ID, @BLO_ID='5', @DESC='23347_SELECTION_GLOBAL_SOUM_2026-08-13 -', @ACC_NO='', @ACH_NO='', @MULT=1, @ORDRE='000050';
EXEC dbo.up_SOUDIV_Update @UniqueId=NULL, @SOU_ID=@SOU_ID, @DIV_ID='0', @ACT_NO='', @DESC='Calque par défaut', @ORDRE='000010';
PRINT '=== 3. Quote copies of the catalogue: ENSEMBLE -> SOUENS, ENSCOMPO -> SOUENSCO, PRODUITS -> SOUPRO (no SQL procedure does this; the application does) ===';
DECLARE @e_id varchar(20), @e_cle varchar(20), @e_desc varchar(60), @e_um varchar(2), @e_prof float, @e_tsec float, @e_tuni float, @e_tum varchar(2), @e_dc datetime, @e_op datetime;
DECLARE c_ens CURSOR LOCAL FOR SELECT ENS_ID, CLEPERS, [DESC], COUUM, PROFIT, TEMPSEC, TEMPUNI, TEMPUM, DATECREE, OLDESTPROD FROM ENSEMBLE WHERE ENS_ID IN ('ENS9E93142F911561EE1','ENSAFF5D05713B179C81');
OPEN c_ens; FETCH NEXT FROM c_ens INTO @e_id,@e_cle,@e_desc,@e_um,@e_prof,@e_tsec,@e_tuni,@e_tum,@e_dc,@e_op;
WHILE @@FETCH_STATUS = 0 BEGIN
  EXEC dbo.up_SOUENS_Update @UniqueId=NULL, @SOU_ID=@SOU_ID, @ENS_ID=@e_id, @ENS_ORG_ID=@e_id, @DESC=@e_desc, @QTETOT=0, @QTETOTSECT=0, @CALCTIMSTP='', @COUUM=@e_um, @TEMPUNI=@e_tuni, @TEMPSEC=@e_tsec, @TEMPUM=@e_tum, @DATECREE=@e_dc, @OLDESTPROD=@e_op, @CLEPERS=@e_cle, @PROFIT=@e_prof;
  FETCH NEXT FROM c_ens INTO @e_id,@e_cle,@e_desc,@e_um,@e_prof,@e_tsec,@e_tuni,@e_tum,@e_dc,@e_op; END; CLOSE c_ens; DEALLOCATE c_ens;
DECLARE @c_ens varchar(20), @c_ordre varchar(6), @c_pro varchar(20), @c_qte float, @c_um varchar(2), @c_tr varchar(1), @c_div float, @c_divum varchar(2);
DECLARE c_cmp CURSOR LOCAL FOR SELECT ENS_ID, ORDRE, PRO_ID, QTE, QTEUM, TYPRATIO, DIV, DIVUM FROM ENSCOMPO WHERE ENS_ID IN ('ENS9E93142F911561EE1','ENSAFF5D05713B179C81') ORDER BY ENS_ID, ORDRE;
OPEN c_cmp; FETCH NEXT FROM c_cmp INTO @c_ens,@c_ordre,@c_pro,@c_qte,@c_um,@c_tr,@c_div,@c_divum;
WHILE @@FETCH_STATUS = 0 BEGIN
  EXEC dbo.up_SOUENSCO_Update @UniqueId=NULL, @SOU_ID=@SOU_ID, @ENS_ID=@c_ens, @PRO_ID=@c_pro, @ORDRE=@c_ordre, @QTE=@c_qte, @QTEUM=@c_um, @TYPRATIO=@c_tr, @DIV=@c_div, @DIVUM=@c_divum;
  FETCH NEXT FROM c_cmp INTO @c_ens,@c_ordre,@c_pro,@c_qte,@c_um,@c_tr,@c_div,@c_divum; END; CLOSE c_cmp; DEALLOCATE c_cmp;
DECLARE @p_id varchar(20), @p_clemanu varchar(30), @p_cledist varchar(20), @p_clepers varchar(20), @p_desc varchar(60), @p_cou float, @p_um varchar(2), @p_qpp float, @p_esc float, @p_prom float, @p_tmp float, @p_tmpum varchar(2), @p_mul float, @p_cat varchar(3), @p_four varchar(2), @p_dcout datetime;
DECLARE c_pro CURSOR LOCAL FOR SELECT PRO_ID, CLEMANU, CLEDIST, CLEPERS, [DESC], COUBRUTUNI, COUUM, QPP, COUESC, PROMCOUNET, TEMPUNI, TEMPUM, MULCOM, CODECAT, CODEFOUR, DATECOUT FROM PRODUITS WHERE PRO_ID IN (SELECT PRO_ID FROM ENSCOMPO WHERE ENS_ID IN ('ENS9E93142F911561EE1','ENSAFF5D05713B179C81')) OR PRO_ID IN ('') ORDER BY PRO_ID;
OPEN c_pro; FETCH NEXT FROM c_pro INTO @p_id,@p_clemanu,@p_cledist,@p_clepers,@p_desc,@p_cou,@p_um,@p_qpp,@p_esc,@p_prom,@p_tmp,@p_tmpum,@p_mul,@p_cat,@p_four,@p_dcout;
WHILE @@FETCH_STATUS = 0 BEGIN
  EXEC dbo.up_SOUPRO_Update @UniqueId=NULL, @SOU_ID=@SOU_ID, @PRO_ID=@p_id, @CLEMANU=@p_clemanu, @CLEDIST=@p_cledist, @CLEPERS=@p_clepers, @DESC=@p_desc, @QTEENS=0, @QTELOT=0, @QTEOTH=0, @CALCTIMSTP='', @COUBRUTUNI=@p_cou, @COUUM=@p_um, @QPP=@p_qpp, @COUESC=@p_esc, @PROMCOUNET=@p_prom, @TEMPUNI=@p_tmp, @TEMPUM=@p_tmpum, @MULCOM=@p_mul, @CODEIMPR='', @CODEFOUR=@p_four, @CODECAT=@p_cat, @DATECOUT=@p_dcout, @DATECOUNET=NULL, @RESCOUNET=0, @QTECOM=0, @QTEACOM=0, @ISVIRT=0, @VIRTCOUNT=0;
  FETCH NEXT FROM c_pro INTO @p_id,@p_clemanu,@p_cledist,@p_clepers,@p_desc,@p_cou,@p_um,@p_qpp,@p_esc,@p_prom,@p_tmp,@p_tmpum,@p_mul,@p_cat,@p_four,@p_dcout; END; CLOSE c_pro; DEALLOCATE c_pro;
PRINT '=== 4. Takeoff lines (SOUREL, TYPERELEVE=P): one per plan x layer x linked group; EXT_ID = GroupID ===';
-- Line GroupID=64 'conduit 3/4 07c12' on plan #5 '23347_SELECTION_GLOBAL_SOUM_2026-08-13 - 5' (23347_SELECTION_GLOBAL_SOUM_2026-08-13 - 5.png), layer 0: 6 elements, 9162.0 px x 1
EXEC dbo.up_SOUREL_Update @UniqueId=NULL, @SOU_ID=@SOU_ID, @BLO_ID='5', @DIV_ID='0', @TYPERELEVE='P', @EXT_ID='64', @ORDRE='000010',
  @TYPEITEM='A', @ITEM_ID='ENSAFF5D05713B179C81', @DESCR='conduit 3/4 07c12', @QTE=9162.0, @SECTION=0, @QTEUM='F', @PROFIT=0, @TYPETAXE='M', @CODEIMPR='',
  @COUTANBRUT=0, @TEMPSUNIT=0, @TEMPSSEC=0, @TEMPSUM='', @PROFITPLUS=0, @PROFITMOIN=0, @ACC_NO='', @ACH_NO='', @ACT_NO='';
-- Line GroupID=65 'conduit 2 33c12' on plan #5 '23347_SELECTION_GLOBAL_SOUM_2026-08-13 - 5' (23347_SELECTION_GLOBAL_SOUM_2026-08-13 - 5.png), layer 0: 3 elements, 7513.0 px x 1
EXEC dbo.up_SOUREL_Update @UniqueId=NULL, @SOU_ID=@SOU_ID, @BLO_ID='5', @DIV_ID='0', @TYPERELEVE='P', @EXT_ID='65', @ORDRE='000020',
  @TYPEITEM='A', @ITEM_ID='ENS9E93142F911561EE1', @DESCR='conduit 2 33c12', @QTE=7513.0, @SECTION=0, @QTEUM='F', @PROFIT=0, @TYPETAXE='M', @CODEIMPR='',
  @COUTANBRUT=0, @TEMPSUNIT=0, @TEMPSSEC=0, @TEMPSUM='', @PROFITPLUS=0, @PROFITMOIN=0, @ACC_NO='', @ACH_NO='', @ACT_NO='';
PRINT '=== 5. Not importable: drawn objects whose group has no EEExchangeData (no ITEM_ID -> nothing to price) ===';
-- 66 objects in 64 groups, e.g.:
--   Counter GroupID=34 'PRISE DEPLACER' plan #2 layer 0: 49 elements
--   Counter GroupID=42 'PLINTHE RELO' plan #2 layer 0: 4 elements
--   Counter GroupID=43 'FIXTURE ENLEVER' plan #3 layer 0: 204 elements
--   Line GroupID=45 'PVC 1po' plan #5 layer 0: 21 elements
--   Counter GroupID=46 'prise' plan #5 layer 0: 23 elements
--   Counter GroupID=47 'prise contrler np' plan #5 layer 0: 14 elements
--   Counter GroupID=48 'MONUMENT PLANCHER D' plan #5 layer 0: 7 elements
--   Counter GroupID=49 'INFORMATIQUE' plan #5 layer 0: 10 elements
PRINT '=== 6. Roll-up: sp_SOUPRO_Quantity_V2 -> SOUPRO.QTEENS / QTEOTH ===';
EXEC dbo.sp_SOUPRO_Quantity_V2 @SOU_ID=@SOU_ID, @REPLACE_FILTER=1, @DoLog=0, @SOUPROLOG='';
SELECT BLO_ID, DIV_ID, EXT_ID, TYPEITEM, ITEM_ID, DESCR, QTE, QTEUM FROM SOUREL WHERE SOU_ID=@SOU_ID ORDER BY ORDRE;
SELECT ENS_ID, ENS_ORG_ID, CLEPERS, [DESC], COUUM FROM SOUENS WHERE SOU_ID=@SOU_ID;
SELECT ENS_ID, PRO_ID, QTE, QTEUM, TYPRATIO, DIV, DIVUM FROM SOUENSCO WHERE SOU_ID=@SOU_ID ORDER BY ENS_ID, ORDRE;
SELECT PRO_ID, COUUM, QTEENS, QTEOTH, QTELOT, CALCTIMSTP FROM SOUPRO WHERE SOU_ID=@SOU_ID ORDER BY PRO_ID;
SELECT SOU_ID, EXTAPP, EXTFILE, UMPLAN, CALCTIMSTP FROM SOUMIS WHERE SOU_ID=@SOU_ID;
PRINT '=== 7. Totals of the material takeoff (sp_SOU_CalculTotaux P, ModeCalcul=C, DoLog=1) ===';
EXEC dbo.sp_SOU_CalculTotaux @SOU_ID=@SOU_ID, @TypeReleve='P', @EE_CALGARY=0, @ModeCalcul='C', @VendantUAvantVendantT=1, @VPM=2, @DoLog=1;
